import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

// Correct paths to the public folder
const sofiaPro = localFont({
  src: "./font/SofiaProRegular.woff2", 
});

const suisseinTl = localFont({
  src: "/font/suisseintl.woff2",  
  variable: "--font-suisseintl"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${sofiaPro.className} ${suisseinTl.className}`}
    >
      <body>{children}</body>
    </html>
  );
}
